baseURL = 'https://blockblog.top/'
languageCode = 'zh-cn'
title = 'GoClub'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookTheme = 'light'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
